server:
  port: 9000

spring:
  application:
    name: migration-app
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://172.27.210.242:30037/migration
    username: migration
    password: migration
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---

management:
  tracing:
    enabled: true


logging:
  level:
    root: info
    org:
      springframework:
        web: DEBUG
        boot.context.properties: DEBUG

migration:
  batch-size: 5
  enabled: true
  mode: NON_INTERACTIVE
  rollback-strategy: NONE
  jobs-package: com.avx.migration.jobs
  executor: SEQUENTIAL
  versions:
    - "1.0.0"
    - "1.1.0"
    - "2.0.0"